### ISSUE TITLE
feat: 자유 게시글 작성 화면 구현

### ISSUE THREAD

**Issue by djswns7** [MofMof-KR/MofMof-FE#5]
## Todo
- [x] 게시판에 우선적으로 구현할 기능 정하기
- [ ] 모바일 레이아웃 구현
- [ ] 백엔드에 요청받을 데이터 정리
- [x] 게시판 글 추가 관련 API 있는지 확인해 볼 것 => draft.js 라이브러리 사용
- [ ] 제목 및 특정 추가명시사항 작성란 구현 (아래 사진 예시) 

![Image](https://user-images.githubusercontent.com/72201211/236132094-d0de2ff7-ff23-406f-99b9-b012a92f64a0.png)
- [ ] URL 삽입기능 구현
- [ ] 이미지 첨부 기능 구현
- [ ] 첨부한 이미지를 글 작성환경에 표시되도록 하기
- [ ] 첨부한 이미지를 글 작성환경에서 제거할 수 있도록 하기(Backspace나 delete 키를 활용할 지 이미지 자체에 제거버튼을 넣을지 고민해볼 것)
- [ ] 동영상 첨부 기능 구현
- [ ] 첨부한 동영상을 글 작성환경에 표시되도록 하기
- [ ] 첨부한 동영상을 글 작성환경에서 제거할 수 있도록 하기(Backspace나 delete 키를 활용할 지 이미지 자체에 제거버튼을 넣을지 고민해볼 것)
- [x] 텍스트 작성 시 이텔릭체, 밑줄, 취소선 등과같은 글자효과(글자 효과는 어떤것들이 필요할지 상의 할 것) 추가기능 구현
- [ ] 사진 또는 동영상 미리보기 기능 구현
- [ ] 완성한 게시물 DB와 연동

## 기타
> - [ ] 투표 or 인원 모으기 UI 삽입 구현(필수기능은 아니나 필요할 것 같음 임시기능)
